name: automated_testing_framework_plugin_firebase
description: Library to use Google's Firebase Realtime Database as a storage mechanism for automated tests and test results.
homepage: https://github.com/peiffer-innovations/automated_testing_framework_plugin_firebase

version: 2.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  automated_testing_framework: ^2.0.0
  automated_testing_framework_models: ^1.0.5+3
  automated_testing_framework_plugin_firebase_storage: ^2.0.0
  convert: ^2.1.1
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  firebase_database: ^6.0.0
  firebase_storage: ^7.0.0
  flutter:
    sdk: flutter
  form_validation: ^1.0.2+1
  intl: ^0.16.1
  json_class: ^1.0.7+2
  logging: ">=0.11.4 <2.0.0"
  meta: ^1.2.4
  static_translations: ^1.0.3+1
  uuid: ^2.2.2

# dependency_overrides:
#   automated_testing_framework:
#     path: ../automated_testing_framework
#   automated_testing_framework_models:
#     path: ../automated_testing_framework_models

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
