name: 'automated_testing_framework_plugin_firebase'
description: "Library to use Google's Firebase Realtime Database as a storage mechanism for automated tests and test results."
homepage: 'https://github.com/peiffer-innovations/automated_testing_framework_plugin_firebase'
version: '5.0.1+3'

environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  automated_testing_framework: '^4.0.7+1'
  automated_testing_framework_models: '^2.0.9+6'
  automated_testing_framework_plugin_firebase_storage: '^5.0.0+14'
  convert: '^3.0.2'
  firebase_auth: '^3.7.0'
  firebase_core: '^1.21.1'
  firebase_database: '^9.1.3'
  firebase_storage: '^10.3.7'
  flutter: 
    sdk: 'flutter'
  form_validation: '^2.1.0+14'
  intl: '^0.17.0'
  json_class: '^2.1.2+9'
  logging: '^1.0.2'
  static_translations: '^2.1.1+10'
  uuid: '^3.0.6'

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'


flutter: 
  uses-material-design: true

ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
