name: automated_testing_framework_plugin_firebase
description: Library to use Google's Firebase Realtime Database as a storage mechanism for automated tests and test results.
homepage: https://github.com/peiffer-innovations/automated_testing_framework_plugin_firebase

version: 1.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  automated_testing_framework: ^1.1.0
  convert: ^2.1.1
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  firebase_database: ^4.0.0
  firebase_storage: ^4.0.0
  form_validation: ^1.0.1
  json_class: ^1.0.6+1
  logging: ^0.11.4
  meta: ^1.1.8
  static_translations: ^1.0.3

# dependency_overrides:
#   automated_testing_framework:
#     path: ../automated_testing_framework

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
